#!/bin/bash
echo 'Will forward all traffic to port 80, onto port 3000'
sudo ssh craig@127.0.0.1 -L 80:127.0.0.1:3000 -N -g -f
echo Forwarding traffic on 80 to 3000, on all interfaces. running this tunnel in the background
